image: flauc/firebase

stages:
  - lint
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - functions/node_modules/
    - client/node_modules/

before_script:
  - npm ci
  - npm --prefix client ci
  - npm --prefix functions ci

Lint Codebase:
  stage: lint
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-lint/
  script:
    - npm run lint

deploy-prod:
  stage: deploy
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-build/
  script:
    - firebase use jaspero-sanghamitra --token $FIREBASE_TOKEN
    - npm run target-setup -- --token $FIREBASE_TOKEN
    - echo export const ENV_CONFIG=$PUBLIC_CONFIG > client/shared/consts/env-config.const.ts
    - firebase functions:config:set instagram.clientsecret=$INSTAGRAM_SECRET instagram.clientid=$INSTAGRAM_ID mailchimp.token=$MAILCHIMP_TOKEN mailchimp.list=MAILCHIMP_LIST sendgrid.token=$SENDGRID_TOKEN stripe.token=$STRIPE_DEV_TOKEN stripe.webhook=$STRIPE_WEBHOOK --token $FIREBASE_TOKEN
    - npm run build
    - npm run deploy -- -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
