export const COUNTRY_CURRENCY = [
  {currency: 'AUD', countries: [
      'AU',
      'CX',
      'CC',
      'HM',
      'KI',
      'NR',
      'NF',
      'TV',
    ]},
  {currency: 'EUR', countries: [
      'AD',
      'AT',
      'BE',
      'CY',
      'EE',
      'FI',
      'FR',
      'GF',
      'TF',
      'DE',
      'GR',
      'GP',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MT',
      'MQ',
      'YT',
      'MC',
      'ME',
      'NL',
      'PT',
      'RE',
      'PM',
      'SM',
      'SK',
      'SI',
      'ES',
    ]},
  {currency: 'GBP', countries: [
      'IM',
      'JE',
      'GS',
      'GB',
    ]},
  {currency: 'HRK', countries: ['HR']},
  {currency: 'USD', countries: ['AS',
      'IO',
      'GU',
      'MH',
      'FM',
      'MP',
      'PW',
      'PR',
      'TC',
      'US',
      'UM',
      'VI',]},
  {currency: 'INR', countries: ['IN']},
];
